edition: 1.0.0
name: 'llm'
access: 'undefined'

services:
  framework:
    component: fc
    props:
      region: 'cn-shenzhen'
      service:
        name: 'llm'
        description: 'LLM Service'
        role: acs:ram::1139396200532432:role/aliyunfcdefaultrole
        vpcConfig:
          vpcId: vpc-wz9qzo60v7tckipg5e5r5
          vswitchIds:
            - vsw-wz9r7kl5szv842l6pj6jj
          securityGroupId: sg-wz9ij4l6v30875qa4hjk
        nasConfig:
          mountPoints:
            - serverAddr: 282cc4b780-iep22.cn-shenzhen.nas.aliyuncs.com
              nasDir: /ollama
              fcDir: /ollama
        logConfig:
          enableRequestMetrics: true
          enableInstanceMetrics: true
          logBeginRule: DefaultRegex
          project: aliyun-fc-cn-shenzhen-743394e2-c05b-5c67-a97a-6687e3e012cc
          logstore: function-log
        customHealthCheckConfig:
          failureThreshold: 3
          httpGetUrl: /api/version
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
      function:
        name: 'ollama'
        description: 'Ollama Container Function'
        runtime: custom-container
        handler: not-used
        timeout: 3600
        caPort: 11434
        cpu: 4
        instanceType: g1
        memorySize: 16384
        gpu: 1
        gpuMemorySize: 16384
        diskSize: 512
        environmentVariables: # 环境变量
#          OLLAMA_MODELS: '/ollama/models'
          OLLAMA_HOME: '/ollama'
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/llldh/ollama:1
        customHealthCheckConfig:
          httpGetUrl: /api/version # 容器自定义健康检查 URL 地址
          initialDelaySeconds: 30 # 容器启动到发起健康检查的延迟
          periodSeconds: 3 # 健康检查周期
          timeoutSeconds: 1 # 健康检查超时时间
          failureThreshold: 3 # 健康检查失败次数阈值
          successThreshold: 1 # 健康检查成功次数阈值
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*