edition: 1.0.0
name: 'llm'
access: 'undefined'

services:
  framework:
    component: fc
    props:
      region: 'cn-shenzhen'
      service:
        name: 'svc2'
        description: 'LLM Service'
        role: acs:ram::1139396200532432:role/aliyunfcdefaultrole
        vpcConfig:
          vpcId: vpc-wz9qzo60v7tckipg5e5r5
          vSwitchIds:
            - vsw-wz9r7kl5szv842l6pj6jj
          securityGroupId: sg-wz9ij4l6v30875qa4hjk
        nasConfig:
          mountPoints:
            - serverAddr: 282cc4b780-iep22.cn-shenzhen.nas.aliyuncs.com
              nasDir: /ollama/models
              fcDir: /ollama/models
      function:
        name: 'fc2'
        description: 'Ollama Container Function'
        runtime: custom-container
        handler: not-used
        timeout: 3600
        gpu: true
        caPort: 11434
        environmentVariables: # 环境变量
          OLLAMA_MODELS: '/ollama/models'
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/llldh/ollama:1
        customHealthCheckConfig:
          httpGetUrl: /api/version # 容器自定义健康检查 URL 地址
          initialDelaySeconds: 30 # 容器启动到发起健康检查的延迟
          periodSeconds: 3 # 健康检查周期
          timeoutSeconds: 1 # 健康检查超时时间
          failureThreshold: 3 # 健康检查失败次数阈值
          successThreshold: 1 # 健康检查成功次数阈值
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*