edition: 1.0.0
name: 'llm'
access: 'undefined'

services:
  framework:
    component: fc
    props:
      region: 'cn-shenzhen'
      service:
        name: 'svc2'
        description: 'LLM Service'
      function:
        name: 'fc2'
        description: 'Ollama Container Function'
        runtime: custom-container
        handler: not-used
        memorySize: 16384
        cpu: 4
        timeout: 3600
        gpu: true
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/llldh/ollama:1
          gpus: all
          port: 11434
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
