edition: 1.0.0
name: my-ollama
access: default

services:
  fc-deploy-test:
    component: devsapp/fc
    props:
      region: cn-shenzhen
      service:
        name: my-service
        description: "My custom service running in a custom container"
      function:
        name: my-function
        description: "Function that runs my custom container"
        runtime: custom-container
        handler: not-used
        memorySize: 16384
        cpu: 4
        timeout: 3600  # Timeout in seconds
        gpu: true
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/llldh/ollama:1
          gpus: all
          port: 11434
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
          customHealthCheck:
            path: /ping
            port: 11434
