edition: 1.0.0
name: ollama-app
access: default

services:
  fc-deploy-test:
    component: fc
    props:
      region: cn-shenzhen
      service:
        name: svc-llm
        description: "LLM Service"
        vpcConfig:
          vpcId: vpc-wz9qzo60v7tckipg5e5r5
          vSwitchIds:
            - vsw-wz9r7kl5szv842l6pj6jj
          securityGroupId: sg-wz9ij4l6v30875qa4hjk
        nasConfig:
          mountPoints:
            - serverAddr: 282cc4b780-iep22.cn-shenzhen.nas.aliyuncs.com
              nasDir: /ollama
              fcDir: /mnt/models
      function:
        name: fc-ollama
        description: "Ollama Container Function"
        runtime: custom-container
        handler: not-used
        memorySize: 16384
        cpu: 4
        disk: 512
        timeout: 120
        gpu: true
        environmentVariables:
          OLLAMA_MODELS: '/mnt/models'
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/llldh/ollama:1
          gpus: all
          port: 11434
          environmentVariables:
            OLLAMA_MODELS: '/mnt/models'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
          customHealthCheck:
            path: /ping
            port: 11434
